spring:
  kafka:
    bootstrap-servers: ${NOTIFICATION_SERVICE_KAFKA_HOST}:${NOTIFICATION_SERVICE_KAFKA_PORT}

  data:
    cassandra:
      keyspace-name: ${NOTIFICATION_SERVICE_CASSANDRA_KEYSPACE}
      #contact-points: my-release-cassandra.default.svc.cluster.local
      contact-points: ${NOTIFICATION_SERVICE_CASSANDRA_HOST}
      port: ${NOTIFICATION_SERVICE_CASSANDRA_PORT}
      password: ${NOTIFICATION_SERVICE_CASSANDRA_PASSWORD}
      username: cassandra
      schema-action: none

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${NOTIFICATION_SERVICE_MAIL_USERNAME}
    password: ${NOTIFICATION_SERVICE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000
          starttls:
            enable: true
config:
  topic:
    send-email: "send-email-topic"

server:
  port: 8005